---
title: "madrid"
author: "EP"
date: "1/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(tabulizer)
```

## 200 Est F

```{r}
the_file <- "../raw_data/LISTADO INICIAL PREINSCRIPCIONES V CTO MASTER INVIERNO 21-22.pdf"
 
dista <- 200
sex <- "Fem"
tipo <- "libre"

temp<-extract_areas(the_file, pages = 2)

estf200 <-tibble(Nombre = temp[[1]][,2],
                Club = temp[[1]][,4],
                Tiempo = temp[[1]][,5]) %>% 
  mutate(Categoria = as.numeric(str_sub(Nombre,-2)),
         Nombre = str_sub(Nombre, end = -3),
         Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)  
  
  
xdata <- estf200
```



## 200 Est M


```{r}


dista <- 200
sex <- "Mas"
tipo <- "libre"



temp<-extract_areas(the_file, pages = c(3,4))

estm200_1 <-tibble(Nombre = temp[[1]][,2],
                Club = temp[[1]][,4],
                Tiempo = temp[[1]][,5],
                Categoria = as.numeric(temp[[1]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)  

estm200_2 <-tibble(Nombre = temp[[2]][,2],
                Club = temp[[2]][,4],
                Tiempo = temp[[2]][,5],
                Categoria = as.numeric(temp[[2]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)  


 estm200 <- estm200_1 %>% rbind(estm200_2) 
  
 xdata <- estf200 %>% rbind(estm200)
```



## 100 braza Femenino

```{r}

dista <- 100
sex <- "Fem"
tipo <- "braza"

temp<-extract_areas(the_file, pages = c(4,5))

brf100_1 <-tibble(Nombre = temp[[1]][,2],
                Club = temp[[1]][,4],
                Tiempo = temp[[1]][,5]) %>% 
  mutate(Categoria = as.numeric(str_sub(Nombre,-2)),
         Nombre = str_sub(Nombre, end = -3),
         Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)  
  
 brf100_2 <-tibble(Nombre = temp[[2]][,2],
                Club = temp[[2]][,4],
                Tiempo = temp[[2]][,5],
                Categoria = as.numeric(temp[[2]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)   

 brf100 <- brf100_1 %>% rbind(brf100_2)
 
  xdata <- estf200 %>% rbind(estm200) %>% 
    rbind(brf100)
```


## 100 Braza masculino

```{r}

dista <- 100
sex <- "Mas"
tipo <- "braza"

temp<-extract_areas(the_file, pages = c(5,6,7))
temp<-extract_areas(the_file, pages = c(5))


bm100_1 <-tibble(Nombre = temp[[1]][,2],
                Club = temp[[1]][,4],
                Tiempo = temp[[1]][,5],
                Categoria = as.numeric(temp[[1]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)   

brm100_2 <-tibble(Nombre = temp[[2]][,2],
                Club = temp[[2]][,4],
                Tiempo = temp[[2]][,5]) %>% 
  mutate(Categoria = as.numeric(str_sub(Nombre,-2)),
         Nombre = str_sub(Nombre, end = -3),
         Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete) 

bm100_3 <-tibble(Nombre = temp[[3]][,2],
                Club = temp[[3]][,4],
                Tiempo = temp[[3]][,5],
                Categoria = as.numeric(temp[[3]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete) 


bm100 <- bm100_1 %>% rbind(brm100_2) %>% rbind(bm100_3)

xdata <- estf200 %>% rbind(estm200) %>% 
    rbind(brf100) %>% rbind(bm100)

```




## 200L Fem


```{r}
dista <- 200
sex <- "Fem"
tipo <- "libre"


temp<-extract_areas(the_file, pages = c(7,8))




lf200_1 <-tibble(Nombre = temp[[1]][,2],
                Club = temp[[1]][,4],
                Tiempo = temp[[1]][,5],
                Categoria = as.numeric(temp[[1]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)   


lf200_2 <-tibble(Nombre = temp[[2]][,2],
                Club = temp[[2]][,4],
                Tiempo = temp[[2]][,5]) %>% 
  mutate(Categoria = as.numeric(str_sub(Nombre,-2)),
         Nombre = str_sub(Nombre, end = -3),
         Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete) 

lf200 <- lf200_1 %>%  rbind(lf200_2)

xdata <- estf200 %>% rbind(estm200) %>% 
    rbind(brf100) %>% rbind(bm100) %>% 
  rbind(lf200)

```

## 200 M Libre masculino

```{r}

dista <- 200
sex <- "Mas"
tipo <- "libre"

temp<-extract_areas(the_file, pages = c(9,10,11))
# temp<-extract_areas(the_file, pages = c(9))


lm200_1 <-tibble(Nombre = temp[[1]][,2],
                Club = temp[[1]][,4],
                Tiempo = temp[[1]][,5],
                Categoria = as.numeric(temp[[1]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete)   

lmm200_2 <-tibble(Nombre = temp[[2]][,2],
                Club = temp[[2]][,4],
                Tiempo = temp[[2]][,5],
                Categoria = as.numeric(temp[[2]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete) 

lm200_3 <-tibble(Nombre = temp[[3]][,2],
                Club = temp[[3]][,4],
                Tiempo = temp[[3]][,5],
                Categoria = as.numeric(temp[[3]][,3])) %>% 
  mutate(Prueba = paste0(dista,"m "),
         Sexo = sex,
         Distancia = dista) %>% 
  separate(Club, c("delete","Club"), " - ") %>% 
  select(-delete) 


lm200 <- lm200_1 %>% rbind(lmm200_2) %>% rbind(lm200_3)

xdata <- estf200 %>% rbind(estm200) %>% 
    rbind(brf100) %>% rbind(bm100) %>% 
  rbind(lf200) %>% rbind(lm200)

```



